spring:
    application:
        name: EUREKA
eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
server:
    port: 8080
